In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
df1=pd.read_csv("/content/drive/MyDrive/Titanic_Train.csv")
df2=pd.read_csv("/content/drive/MyDrive/Titanic_Test.csv")

In [ ]:
df1.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
df2.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [ ]:
from sklearn.preprocessing import LabelEncoder

label_encoder = LabelEncoder()

df1['Sex'] = label_encoder.fit_transform(df1['Sex'])
df2['Sex'] = label_encoder.transform(df2['Sex'])

df1['Embarked'] = label_encoder.fit_transform(df1['Embarked'])
df2['Embarked'] = label_encoder.transform(df2['Embarked'])

In [ ]:
df1.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

In [ ]:
df2.isnull().sum()

PassengerId      0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [ ]:
df1.fillna(0,inplace=True)
df2.fillna(0,inplace=True)

In [ ]:
df1.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
df2.isnull().sum()

PassengerId    0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
features = ['Pclass', 'Age', 'SibSp', 'Parch', 'Fare','Sex','Embarked']
X_train = df1[features]
y_train = df1['Survived']
X_test = df2[features]

In [ ]:
from sklearn.naive_bayes import GaussianNB
nb= GaussianNB()
nb.fit(X_train, y_train)

GaussianNB()

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
y_train_pred = nb.predict(X_train)
y_test_pred = nb.predict(X_test)
accuracy = accuracy_score(y_train, y_train_pred)
print(f"Accuracy on the training dataset: {accuracy}")

Accuracy on the training dataset: 0.7890011223344556

In [ ]:
from re import X
n=[]
p=float(input("Enter the p_class:"))
n.append(p)
a=float(input("Enter the Age:"))
n.append(a)
s=float(input("Enter the sibsp:"))
n.append(s)
h=float(input("Enter the parch:"))
n.append(h)
f=float(input("Enter the Fare:"))
n.append(f)
x=float(input("Enter the sex:"))
n.append(x)
e=float(input("Enter the Embarked:"))
n.append(e)
res=np.array(n)
n_res=res.reshape(1,-1)
pred=nb.predict(n_res)
result=pred[0]
if result == 0:
  print("Not Survived")
elif result == 1:
  print("Survived")

Enter the p_class:3
Enter the Age:34.2
Enter the sibsp:0
Enter the parch:0
Enter the Fare:10
Enter the sex:1
Enter the Embarked:1
Not Survived

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(